export const COPY = {
  title: ['Your plan. Your rhythm.', '你的计划，你的节奏。'],
  intro: ['Start with a structure. Fill in what you intend to run, review the details, then take it to PacerMind.', '从一个结构开始，填写你想跑的内容，核对细节，再交给 PacerMind 承接。'],
  badge: ['LOCAL EDITOR · PREVIEW', '本地编辑器 · 预览版'],
  local: ['Your draft stays in this browser. No AI requests, accounts or cloud sync. Templates provide structure; every amount and effort target is yours.', '草稿保存在此浏览器，不发送 AI 请求，不需要账号，不云端同步。模板只提供结构，距离、时长与强度都由你设定。'],
  setup: ['01 / Set the direction', '01 / 设定方向'],
  schedule: ['02 / Arrange your days', '02 / 安排每一天'],
  review: ['03 / Read the plan', '03 / 看清计划'],
  export: ['04 / Take it to the App', '04 / 交给 App'],
  planTitle: ['Plan title', '计划标题'],
  goal: ['Your intention', '你的意图'],
  notes: ['Plan notes', '计划备注'],
  start: ['First week starts', '首周开始日期'],
  weekStart: ['Week starts on', '一周开始于'],
  monday: ['Monday', '周一'],
  sunday: ['Sunday', '周日'],
  mode: ['Planning horizon', '计划范围'],
  single: ['One week', '单周计划'],
  long: ['Race phases', '长期备赛阶段'],
  dateHint: ['Choose the actual Monday or Sunday. No dates are assumed.', '请明确选择周一或周日的日期，不自动猜测。'],
  raceName: ['Race name', '比赛名称'],
  raceDate: ['Race date', '比赛日期'],
  raceDistance: ['Race distance', '比赛距离'],
  raceTime: ['Optional goal time (seconds)', '可选目标时间（秒）'],
  phases: ['Phases', '阶段'],
  phase: ['Phase', '阶段'],
  role: ['Week role', '周角色'],
  focus: ['Your focus for these weeks', '这些周的个人重点'],
  weeks: ['Weeks', '周数'],
  addPhase: ['Add phase', '添加阶段'],
  remove: ['Remove', '删除'],
  direction: ['Future weeks can stay as direction. Only the selected, fully confirmed weeks become concrete App days.', '未来周可以只保留方向。只有选中且逐日确认的周，才会成为 App 的具体日程。'],
  templates: ['Structure library', '结构库'],
  templateHint: ['Select a template, then choose a pending day. No distance, pace or repeat count is prescribed.', '先选模板，再选待确认的日期。距离、配速与重复次数不会自动填写。'],
  add: ['Add workout', '添加训练'],
  edit: ['Edit', '编辑'],
  pending: ['Pending confirmation', '待确认'],
  rest: ['Rest · confirmed', '休息 · 已确认'],
  markRest: ['Confirm rest', '确认休息'],
  resetDay: ['Clear day', '清空当天'],
  race: ['Race event', '比赛事件'],
  addRace: ['Add target race event', '加入目标比赛事件'],
  dayNotes: ['Day notes', '当天备注'],
  eventName: ['Event name', '事件名称'],
  eventDistance: ['Event distance', '事件距离'],
  eventTime: ['Goal time (seconds)', '目标时间（秒）'],
  enableEvent: ['Include race event', '包含比赛事件'],
  workout: ['Workout', '训练'],
  workoutTitle: ['Workout title', '训练标题'],
  type: ['Workout type', '训练类型'],
  description: ['Workout notes', '训练备注'],
  environment: ['Environment (optional)', '场地（可选）'],
  outdoor: ['Outdoor', '室外'],
  indoor: ['Indoor', '室内'],
  startTime: ['Start time (optional)', '开始时间（可选）'],
  unspecified: ['Unspecified', '未指定'],
  warmup: ['Warmup', '热身'],
  cooldown: ['Cooldown', '放松'],
  addWarmup: ['Add warmup', '添加热身'],
  addCooldown: ['Add cooldown', '添加放松'],
  block: ['Block', '训练组'],
  repeat: ['Repeats (1–30)', '重复次数（1–30）'],
  label: ['Block label', '训练组标签'],
  segment: ['Segment', '训练段'],
  work: ['Work', '工作段'],
  recovery: ['Recovery', '恢复段'],
  metric: ['Measure', '计量方式'],
  distance: ['Distance', '距离'],
  duration: ['Duration', '时长'],
  amount: ['Amount', '数值'],
  unit: ['Unit', '单位'],
  paceFast: ['Fast pace (min:sec or decimal min)', '最快配速（分:秒 或十进制分）'],
  paceSlow: ['Slow pace (min:sec or decimal min)', '最慢配速（分:秒 或十进制分）'],
  paceUnit: ['Pace per', '配速单位'],
  rpe: ['RPE (optional, 1–10)', 'RPE（可选，1–10）'],
  zone: ['HR zone (optional, Z1–Z5)', '心率区间（可选，Z1–Z5）'],
  addWork: ['Add work segment', '添加工作段'],
  addRecovery: ['Add recovery segment', '添加恢复段'],
  addBlock: ['Add block', '添加训练组'],
  segmentHint: ['5:30 means 5.5 minutes; 5.30 means 5 minutes 18 seconds. Both pace bounds enable a calculated range. A single bound remains a target only. Each repeat includes all its segments, including recovery.', '5:30 是 5.5 分钟；5.30 是 5 分 18 秒。填写两端配速可计算范围，单端只作为目标。每次重复都包含全部训练段，包括恢复段。'],
  save: ['Save draft changes', '保存草稿修改'],
  cancel: ['Cancel', '取消'],
  confirm: ['Confirm change', '确认变更'],
  undo: ['Undo', '撤销'],
  copy: ['Copy workout', '复制训练'],
  move: ['Move workout', '移动训练'],
  destination: ['Destination day', '目标日期'],
  limit: ['App JSON supports one workout and one optional race event per day. A second workout must stay outside this export; it is never merged silently.', 'App JSON 每天支持一课训练与一个可选比赛事件。同日第二课暂不能导出，不会静默合并。'],
  conflict: ['Destination already has a workout or confirmed rest. Resolve it first.', '目标日期已有训练或已确认休息，请先处理冲突。'],
  previewChange: ['Review this change', '预览此次变更'],
  datesChange: ['Dates are tied to week slots. Existing workouts move with their slot; nothing is silently deleted.', '日程绑定周内位置。已有训练会随位置移动，不会静默删除。'],
  changedDates: ['Affected scheduled days', '受影响的已安排日期'],
  outside: ['Days outside the new horizon', '超出新范围的日期'],
  outsideHint: ['Keep these days in the draft or move them before export. They block App export until resolved.', '这些日程仍保留在草稿中。导出前请移动或清理，否则会阻止 App 导出。'],
  from: ['Export from week', '导出起始周'],
  to: ['Through week', '至第几周'],
  preview: ['Validate & preview JSON', '校验并预览 JSON'],
  copyJSON: ['Copy App JSON', '复制 App JSON'],
  download: ['Download JSON backup', '下载 JSON 备份'],
  importSteps: ['In PacerMind: Plan → import from clipboard → preview → confirm. Align the App’s week-start setting. The App confirms conflicts before replacing plans in this date window.', '在 PacerMind：计划 → 从剪贴板导入 → 预览 → 确认。请让 App 的周开始设置一致。App 会在替换此日期范围的计划前确认冲突。'],
  backupOnly: ['The downloaded file is a backup. File import and automatic opening in the App are not available here.', '下载文件仅供备份。本页不提供 App 文件导入或自动打开。'],
  ready: ['Validated against the App schema. Review the snapshot below before copying.', '已通过 App schema 校验，请检查下方快照再复制。'],
  blocked: ['Resolve the following before App export. Pending days are never changed into rest.', '请先处理以下问题，再导出到 App。待确认日期不会被改成休息。'],
  stale: ['Draft changed. Validate again to produce a new snapshot.', '草稿已修改，请重新校验生成快照。'],
  clipboard: ['Clipboard unavailable. JSON selected below: copy it manually.', '剪贴板不可用，已选中下方 JSON，请手动复制。'],
  copied: ['App JSON copied. Continue in PacerMind.', 'App JSON 已复制，请在 PacerMind 中继续。'],
  invalid: ['Draft restored, with pending fields. Review and validate before export.', '已恢复草稿，含待确认字段。请核对并校验后再导出。'],
  saved: ['Saved locally', '已保存到本地'],
  saveFailed: ['Local saving is unavailable. Keep this page open and download a draft backup.', '本地保存不可用。请保持页面打开，并下载草稿备份。'],
  backup: ['Download draft backup', '下载草稿备份'],
  restore: ['Restore draft backup', '恢复草稿备份'],
  clear: ['Clear draft', '清空草稿'],
  clearHint: ['Download a draft backup first if you need it. Clearing can be undone during this visit.', '如需保留，请先下载草稿备份。本次访问内可以撤销清空。'],
  restoreHint: ['Backup version 1 only, up to 1.5 MB. Restore replaces the current draft after this preview. App JSON is a separate format.', '仅接受第 1 版草稿备份，最大 1.5 MB。确认此预览后会替换当前草稿。App JSON 是另一种格式。'],
  badBackup: ['Backup is invalid, too large or from an unsupported version. Current draft was kept.', '备份无效、过大或版本不支持。当前草稿已保留。'],
  tabs: ['Another tab saved a different draft. Local saving is paused; choose which version to keep.', '另一个标签页保存了不同草稿。本页暂停保存，请明确选择保留哪一版。'],
  loadOther: ['Review other tab’s draft', '预览另一标签页的草稿'],
  keepThis: ['Keep this tab’s draft', '保留本页草稿'],
  corrupt: ['Saved data could not be read. Saving is paused to preserve it. Download the stored data or explicitly start a new draft.', '已有保存数据无法读取。为保留原始数据，暂停保存。请下载原始数据，或明确新建草稿。'],
  rawBackup: ['Download stored data', '下载原始保存数据'],
  fresh: ['Start a new draft', '新建草稿'],
  analysisHint: ['Arithmetic, not a coaching verdict. Unknown components stay visible; races are separate. Planned values do not describe your health or readiness.', '这里只做计算，不给教练结论。未知部分会明确显示，比赛单独统计。计划数值不代表健康或备赛状态。'],
  known: ['Known subtotal', '已知部分小计'],
  unknown: ['Unknown components', '未知训练段'],
  derived: ['Pace-derived range', '由配速推算的范围'],
  pendingDays: ['Pending days', '待确认日期'],
  quality: ['Quality sessions by type', '按课型标记的质量课'],
  qualityHint: ['Tempo, threshold, intervals and race-like types count here. This classification cannot establish actual intensity.', '此处统计节奏、阈值、间歇与模拟比赛课型，不能据此判断实际强度。'],
  raceLoad: ['Race distance (separate)', '比赛距离（单列）'],
  recoveryLoad: ['Explicit recovery distance', '明确的恢复段距离'],
  growth: ['Week-over-week distance', '周距离变化'],
  incomparable: ['Not comparable', '无法比较'],
  reference: ['Personal comparison threshold (%)', '个人比较阈值（%）'],
  over: ['Above your reference', '超过你设定的参考值'],
  gaps: ['Quality-session date gaps', '质量课日期间隔'],
  gapHint: ['Calendar-day difference, not recovery hours. No safe/unsafe classification.', '仅为日历日差值，不代表恢复小时数，不做安全判定。'],
  ruleTitle: ['Calculation notes · rules v1', '计算说明 · 规则 v1'],
  ruleDistance: ['D1: sum distance segments × repeats; warmup/cooldown once. Time segments only yield distance when both pace bounds exist.', 'D1：距离段 × 重复次数求和，热身与放松各一次。时长段只有两端配速齐全才推算距离。'],
  ruleGrowth: ['G1: compare consecutive complete weeks with exact distance and a nonzero previous week. Pending, unknown or pace-derived totals have no percentage. The editable 10% reference is not a safety rule.', 'G1：仅比较相邻完整周、明确距离且前周非零的情况。待确认、未知或推算总量不计算百分比。可改的 10% 参考值不是安全规则。'],
  taper: ['Taper view: review the actual distance trend in taper-labelled weeks. No automatic reduction, peak or race prescription is generated.', '减量视图：查看标记为减量周的实际距离趋势，不自动生成减量、峰值或比赛处方。'],
  noPace: ['No pace assumed', '未预设配速'],
  empty: ['No concrete days yet', '尚无具体日程'],
  previous: ['Previous week', '上一周'],
  next: ['Next week', '下一周'],
  week: ['Week', '第'],
  of: ['of', '/'],
  unavailable: ['Schema unavailable. Retry by reloading; App export remains disabled.', 'Schema 加载失败，请刷新重试。App 导出已停用。']
};
export const LABELS = {
  type: {
    easy: ['Easy', '轻松'],
    aerobic: ['Aerobic', '有氧'],
    steady: ['Steady', '稳定跑'],
    long_run: ['Long run', '长距离'],
    tempo: ['Tempo', '节奏'],
    threshold: ['Threshold', '阈值'],
    intervals: ['Intervals', '间歇'],
    race_like: ['Race-like', '模拟比赛'],
    recovery: ['Recovery', '恢复']
  },
  phase: {
    base: ['Base', '基础'],
    build: ['Build', '提升'],
    peak: ['Peak', '峰值'],
    taper: ['Taper', '减量'],
    race: ['Race', '比赛'],
    free: ['Free / return', '自由与回归']
  },
  role: {
    establish: ['Establish', '建立'],
    maintain: ['Maintain', '维持'],
    develop: ['Develop', '发展'],
    consolidate: ['Consolidate', '巩固'],
    cutback: ['Cutback', '回撤'],
    taper: ['Taper', '减量'],
    race: ['Race', '比赛'],
    return: ['Return', '回归']
  },
  race: {
    '5k': ['5 km', '5 公里'],
    '10k': ['10 km', '10 公里'],
    hm: ['Half marathon', '半马'],
    fm: ['Marathon', '全马'],
    '100k': ['100 km', '100 公里'],
    custom: ['Custom · distance unknown', '自定义 · 距离未知']
  }
};
export const ERRORS = {
  amount: ['Enter a positive amount.', '请填写正数数值。'],
  unit: ['Confirm the unit.', '请确认单位。'],
  kind: ['Confirm the segment kind.', '请确认训练段类型。'],
  pace: ['Pace must be a positive decimal or min:sec.', '配速须为正数或分:秒。'],
  paceOrder: ['Fast pace must be no slower than slow pace.', '最快配速不能慢于最慢配速。'],
  rpe: ['RPE must be an integer from 1 to 10.', 'RPE 须为 1–10 的整数。'],
  zone: ['Use Z1–Z5, or a range such as Z2-Z3.', '请用 Z1–Z5 或 Z2-Z3 这样的范围。'],
  type: ['Choose a supported workout type.', '请选择支持的训练课型。'],
  workoutTitle: ['Workout title is required, up to 120 characters.', '请填写训练标题，不超过 120 字符。'],
  blocks: ['Add a workout block.', '请添加训练组。'],
  repeat: ['Set an integer repeat count from 1 to 30.', '请填写 1–30 的整数重复次数。'],
  segments: ['Add a segment to each block.', '每组须至少包含一段。'],
  startDate: ['Confirm a real start date.', '请确认有效开始日期。'],
  weekStart: ['Start date must match your Monday/Sunday preference.', '开始日期须与周一/周日偏好一致。'],
  title: ['Plan title is required, up to 120 characters.', '计划标题必填，不超过 120 字符。'],
  goal: ['Your intention is required, up to 500 characters.', '个人意图必填，不超过 500 字符。'],
  horizon: ['The horizon must contain 1–160 weeks.', '计划须包含 1–160 周。'],
  window: ['Choose an ordered export window within the horizon.', '请选择范围内顺序正确的导出周。'],
  outside: ['Resolve scheduled days outside the horizon.', '请处理范围外的已安排日程。'],
  raceDate: ['Race date must be within the phase horizon.', '比赛日期须在阶段范围内。'],
  race: ['Confirm the race name and supported distance.', '请确认比赛名称与距离。'],
  stageLength: ['Each phase needs 1–160 whole weeks.', '每阶段须为 1–160 个完整周。'],
  focus: ['Write your own phase focus, up to 500 characters.', '请填写阶段重点，不超过 500 字符。'],
  stage: ['Choose supported phase and role values.', '请选择支持的阶段与周角色。'],
  revision: ['Program identity or revision is invalid.', '路线标识或修订号无效。'],
  raceWeek: ['The race date needs a week with the Race role.', '比赛所在周须设为比赛角色。'],
  pending: ['Confirm this day as rest, workout or race.', '请将此日明确为休息、训练或比赛。'],
  restConflict: ['Rest cannot share a day with a workout or race.', '休息日不能同时包含训练或比赛。'],
  raceTime: ['Goal time must be a positive whole number of seconds.', '目标时间须为正整数秒。'],
  schema: ['App schema constraint failed at this field.', '此字段未通过 App schema 约束。'],
  schemaUnavailable: ['App schema could not be loaded.', 'App schema 未能加载。']
};
